CREATE DATABASE inlock_games_tarde;
GO

USE inlock_games_tarde;
GO

CREATE TABLE ESTUDIO (
idEstudio INT PRIMARY KEY IDENTITY(1,1),
nomeEstudio VARCHAR(50) NOT NULL UNIQUE
);
GO

CREATE TABLE JOGOS (
idJogo INT PRIMARY KEY IDENTITY(1,1),
nomeJogo VARCHAR(50) NOT NULL UNIQUE,
descricao VARCHAR(200) NOT NULL,
dataLancamento SMALLDATETIME NOT NULL,
valor SMALLMONEY NOT NULL,
idEstudio INT FOREIGN KEY REFERENCES ESTUDIO(idEstudio)
);
GO

CREATE TABLE TIPOUSUARIO (
idTipoUsuario TINYINT PRIMARY KEY IDENTITY(1,1),
titulo VARCHAR(20) NOT NULL, 
);
GO

CREATE TABLE USUARIO (
idUsuario INT PRIMARY KEY IDENTITY(1,1),
idTipoUsuario TINYINT FOREIGN KEY REFERENCES TIPOUSUARIO (idTipoUsuario),
email VARCHAR(256) UNIQUE NOT NULL,
senha VARCHAR(256) NOT NULL
);
GO 